spring.application.name=wazejob
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=rm556630
spring.datasource.password=050805
spring.jpa.hibernate.ddl-auto=create
security.jwt.secret=050805fiapGS
security.jwt.issuer=wazejob-api
security.jwt.expiration-hours=12
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
