package com.challenge.wazejob.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Size;
import lombok.Data;

@Data
@Schema(description = "Payload for updating an existing track")
public class TrackUpdateDTO {

    @Size(max = 255, message = "Title must not exceed 255 characters")
    @Schema(description = "Track title", example = "Backend Java Specialist")
    private String title;

    @Size(max = 2000, message = "Description must not exceed 2000 characters")
    @Schema(description = "Detailed description", example = "Track focused on mastering Java and Spring Boot")
    private String description;

    @Size(max = 4000, message = "User prompt must not exceed 4000 characters")
    @Schema(description = "Prompt provided by the user", example = "Quero aprender backend com Java e cloud")
    private String userPrompt;

    @Size(max = 4000, message = "AI prompt must not exceed 4000 characters")
    @Schema(description = "Prompt generated by AI", example = "Plano sugerido pela IA com foco em APIs REST")
    private String aiPrompt;

    @Schema(description = "Completion percentage", example = "65")
    private Integer completedPercentage;
}

