package com.challenge.wazejob.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Track data returned in responses")
public class TrackResponseDTO {

    @Schema(description = "Track identifier", example = "123e4567-e89b-12d3-a456-426614174000")
    private String trackId;

    @Schema(description = "Owner user identifier", example = "987e1111-e89b-12d3-a456-426614174000")
    private String userId;

    @Schema(description = "If present, indicates the track this one was forked from")
    private String forkedFromId;

    @Schema(description = "Track title", example = "Backend Java Specialist")
    private String title;

    @Schema(description = "Detailed description", example = "Track focused on mastering Java and Spring Boot")
    private String description;

    @Schema(description = "Prompt provided by the user", example = "Quero aprender backend com Java e cloud")
    private String userPrompt;

    @Schema(description = "Prompt generated by AI", example = "Plano sugerido pela IA com foco em APIs REST")
    private String aiPrompt;

    @Schema(description = "Completion percentage", example = "65")
    private Integer completedPercentage;

    @Schema(description = "Creation timestamp", example = "2025-01-15T10:30:00")
    private String createdAt;

    @Schema(description = "Last update timestamp", example = "2025-01-20T18:45:00")
    private String updatedAt;
}
